/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package toolchain

class App {
    String getGreeting() {
        return "Hello World from ${System.getProperty("java.version")}!"
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
